### ISSUE TITLE
Provider is not working in root component level

### ISSUE THREAD

**Issue by saswat3115** [alex-cory/use-http#221] opened 2020-03-27 09:56 UTC
If my root component is App.tsx and am using Provider in this, then my child component useFetch is not taking base url.

**Comment by alex-cory** [comment] 2020-03-27 18:02
Could you make a [codesandbox](https://codesandbox.io/) reproducing the bug please

**Comment by alex-cory** [comment] 2020-03-30 19:42
closing this. I am not able to reproduce this.

**Closed by alex-cory** 2020-03-30 19:42 UTC
